name: tafeito_flutter
description: TaFeito Flutter app.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  firebase_auth: ^6.5.2
  firebase_core: ^4.10.0
  flutter:
    sdk: flutter
  flutter_secure_storage: ^10.3.1
  google_fonts: ^8.1.0
  http: ^1.2.2
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
